<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-04 07:04
=======
# Generated by Django 5.0.1 on 2024-02-01 09:15
>>>>>>> fb50bd764cbec7a56688593b44ce28f451dd53e0

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
