# Generated by Django 5.0.4 on 2024-05-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
