# Generated by Django 5.0.4 on 2024-05-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_post_comment_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
    ]
